### ISSUE TITLE
After 5 eliminate_methods! patterns given, all output is blank

### ISSUE THREAD

**Issue by krainboltgreene** [ruby-prof/ruby-prof#168] opened 2015-09-02 08:21 UTC
``` ruby
result.eliminate_methods!([/Array/, /Hash/, /Class/, /Scrawl/, /Enumerable/])

```

== Fine

``` ruby
result.eliminate_methods!([/Array/, /Hash/, /Class/, /Scrawl/, /Enumerable/, /Regexp/])
```

=== No printing

This has been tested with any class name, using the `GraphPrinter`.

My example:

``` ruby
require "ruby-prof"
require "earhart"

result = RubyProf.profile do
  pattern = Earhart::Pattern.new(verb: "GET", resource: "/persons/1")
  route = Earhart::Route.new(pattern, Object)
  routes = Earhart::Routes.new([route])
  routes.find("verb=\"GET\" resource=\"/persons/1\"")
end

result.eliminate_methods!([/Array/, /Hash/, /Class/, /Scrawl/, /Enumerable/, /Regexp/])

if ENV["PROFILE_NOTE"]
  RubyProf::GraphPrinter.new(result).print(STDOUT, {})
else
  RubyProf::MultiPrinter.new(result).print(path: File.join("tmp"), profile: File.basename(__FILE__))
end
```

(Really, I think this just shows a `focus_signature!(...)` method could be useful. A whitelist instead of a blacklist.

**Comment by skaes** [comment] 2015-12-06 12:30
I ran your example program and could not reproduce the issue. Therefore closing it.

**Closed by skaes** 2015-12-06 12:30 UTC
