### ISSUE TITLE
Unusable while profiling specs

### ISSUE THREAD

**Issue by dnagir** [ruby-prof/ruby-prof#148] opened 2014-09-03 22:22 UTC
Hi,

I've been trying to use ruby-prof to profile our test-suit (rspec+rails).

But unfortunately it is absolutely unusable.
After running for 5 mins or so and going through first few hundred specs only (out of ~8000+) the process eats up up to 50GB of virtual memory and I literally have to kill or in some occasions reboot the machine.

I'm not sure what's causing it. But I doesn't even get to dumping the results.

I use the following to enable the profiling:

```ruby
# spec/support/profiler.rb
if ENV['PROF']
  require 'ruby-prof'

  RubyProf.start

  at_exit do
    result = RubyProf.stop

    puts 'Writing callstack profile results'
    File.open('./tmp/prof-callstack.html', 'w') { |file| RubyProf::CallStackPrinter.new(result).print(file) }

    puts 'Writing graph profile results'
    File.open('./tmp/prof-graph.html', 'w') { |file| RubyProf::GraphHtmlPrinter.new(result).print(file) }
  end
end
```

with the ruby `ruby-2.1.2-railsexpress` (due to #130).

I accept that the profiler makes it slower and requires more memory, but what I'm seeing is out of ordinary and looks like a bug to me.

I'm not sure what my options are and would appreciate any suggestions.

**Comment by skaes** [comment] 2015-01-16 13:13
I'm sorry to say, but without a reproducible test case we can't make any progress on this ticket.

Closing it.

**Closed by skaes** 2015-01-16 13:13 UTC

**Comment by davidsoncasey** [comment] 2017-08-11 16:11
@skaes I'm runnning into a similar issue. I'll see if I can put together a reproducible case. I'd love to be able to use ruby-prof to help diagnose slow specs.

**Comment by skaes** [comment] 2017-08-13 09:26
@davidsoncasey I'm sorry to hear you have these problems. I have never used ruby-prof to profile a complete ruby test suite for a large app.

I would probably try to measure the runtime of a individual tests using some other approach. I think both rspec and minitest offer drivers to report the runtime of individual tests. I would find the slow ones and then profile them individually. Also, I'd suggest to not start ruby-prof before all of the framework of you app has been loaded. This will reduce memory usage and will, due to reduced GC, probably also reduce overall runtime.
