### ISSUE TITLE
No such file or directory @ rb_sysopen

### ISSUE THREAD

**Issue by asit569** [ruby-prof/ruby-prof#192] opened 2016-05-12 16:01 UTC
I am getting this error when running ruby app.rb 

pi@raspberrypi:~/waterpi-web $ ruby app.rb
/home/pi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/mqtt-0.3.1/lib/mqtt/client.rb:198:in `initialize': No such file or directory @ rb_sysopen - /home/pi/waterpi-web/certs/home/pi/waterpi-web/certs/private.pem.key (Errno::ENOENT)
        from /home/pi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/mqtt-0.3.1/lib/mqtt/client.rb:198:in `open'
        from /home/pi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/mqtt-0.3.1/lib/mqtt/client.rb:198:in `key_file='
        from /home/pi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/mqtt-0.3.1/lib/mqtt/client.rb:168:in `block in initialize'
        from /home/pi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/mqtt-0.3.1/lib/mqtt/client.rb:167:in `each_pair'
        from /home/pi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/mqtt-0.3.1/lib/mqtt/client.rb:167:in `initialize'
        from /home/pi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/mqtt-0.3.1/lib/mqtt/client.rb:92:in `new'
        from /home/pi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/mqtt-0.3.1/lib/mqtt/client.rb:92:in `connect'
        from /home/pi/waterpi-web/boot.rb:40:in `<top (required)>'
        from /home/pi/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /home/pi/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from app.rb:3:in `<main>'

source code-https://github.com/demirhanaydin/waterpi-web

**Comment by skaes** [comment] 2016-05-12 18:17
how is this related to ruby-prof?

**Comment by njh** [comment] 2016-05-12 21:51
Duplicate of njh/ruby-mqtt#76

**Comment by skaes** [comment] 2016-05-13 06:33
@asit569 your Gemfile doesn't even include ruby-prof. Sorry, but I'm not able to help you with your personal project.

**Closed by skaes** 2016-05-13 06:33 UTC
