### ISSUE TITLE
call_tree_printer::print has wrong signature

### ISSUE THREAD

**Issue by Sequoia** [ruby-prof/ruby-prof#203] opened 2016-09-29 14:56 UTC
# What I'm doing

Creating a call tree profile of a jekyll build:

```
$ bundle exec ruby-prof --file=stack.out /usr/local/lib/ruby/gems/2.3.0/gems/jekyll-3.2.1/exe/jekyll --printer=call_tree -- build
```
# Start case

<details>
  <summary>

❌ .../call_tree_printer.rb:46:in `print': wrong number of arguments (given 2, expected 0..1)</summary>

```
Configuration file: /Users/sequoia/tmp/myblog/_config.yml
Configuration file: /Users/sequoia/tmp/myblog/_config.yml
            Source: /Users/sequoia/tmp/myblog
       Destination: /Users/sequoia/tmp/myblog/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
                    done in 0.764 seconds.
 Auto-regeneration: disabled. Use --watch to enable.
/usr/local/lib/ruby/gems/2.3.0/gems/ruby-prof-0.16.2/lib/ruby-prof/printers/call_tree_printer.rb:46:in `print': wrong number of arguments (given 2, expected 0..1) (ArgumentError)
    from /usr/local/lib/ruby/gems/2.3.0/gems/ruby-prof-0.16.2/bin/ruby-prof:329:in `block (3 levels) in <top (required)>'
    from /usr/local/lib/ruby/gems/2.3.0/gems/ruby-prof-0.16.2/bin/ruby-prof:328:in `open'
    from /usr/local/lib/ruby/gems/2.3.0/gems/ruby-prof-0.16.2/bin/ruby-prof:328:in `block (2 levels) in <top (required)>'
    from /usr/local/lib/ruby/gems/2.3.0/gems/ruby-prof-0.16.2/bin/ruby-prof:324:in `chdir'
    from /usr/local/lib/ruby/gems/2.3.0/gems/ruby-prof-0.16.2/bin/ruby-prof:324:in `block in <top (required)>'
```

</details>
# Change

`/usr/local/lib/ruby/gems/2.3.0/gems/ruby-prof-0.16.2/lib/ruby-prof/printers/call_tree_printer.rb`

``` diff
      end
    end

-    def print(options = {})
+    def print(output = STDOUT, options = {})
      @output = output
      setup_options(options)
```
# Fixed

<details>
  <summary>

✅ **Success**</summary>

```
$ bundle exec ruby-prof --file=stack.out /usr/local/lib/ruby/gems/2.3.0/gems/jekyll-3.2.1/exe/jekyll --printer=call_tree -- build
Configuration file: /Users/sequoia/tmp/myblog/_config.yml
Configuration file: /Users/sequoia/tmp/myblog/_config.yml
            Source: /Users/sequoia/tmp/myblog
       Destination: /Users/sequoia/tmp/myblog/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
                    done in 0.763 seconds.
 Auto-regeneration: disabled. Use --watch to enable.
```

</details>
# More info
#198 Raises this same issue and was closed, but **the problem I describe herein is not resolved**.

**Comment by joevandyk** [comment] 2016-10-17 19:40
Seeing this as well

**Comment by skaes** [comment] 2016-10-19 06:39
The signature is correct. What's wrong is that the ruby-prof script calls it incorrectly.

**Comment by skaes** [comment] 2016-10-19 06:44
Fixed in 837edf447914663d0100e5599ab8c44f81f0eae0 . Please test.

**Comment by sadaf2605** [comment] 2016-10-23 08:27
I am getting same error.

**Comment by skaes** [comment] 2016-10-23 16:14
@sadaf2605 did you use the master branch?

**Comment by alexandru-calinoiu** [comment] 2016-10-24 19:03
I am getting the same error also using the master branch.

**Comment by alexandru-calinoiu** [comment] 2016-10-24 19:15
Of course it does not work because this fix is not on master, I've patched the gem locally and all seems to be fine now.

**Comment by skaes** [comment] 2016-10-27 06:44
@alexandru-calinoiu patch above is not on master, because the problem isn't the signature, it's how ruby-prof instantiates the printer. Bot all printers have the same signature: this is intentional.

**Closed** 2017-03-19 21:13 UTC

**Comment by frenkel** [comment] 2017-10-17 08:50
@skaes Will you release a version on rubygems.org that contains the fix?

**Comment by jywarren** [comment] 2017-12-11 20:56
Hi, we're seeing this on an instance in https://github.com/publiclab/plots2/pull/1861 -- I see there's a reason this hasn't been merged, but is there a recommended way forward for people seeing this error such as we are in our Travis setup? The linked PR shows this happen in a Travis log: https://travis-ci.org/publiclab/plots2/builds/314577861

Thanks!

**Comment by philrosenstein** [comment] 2017-12-20 23:27
just trying to add some performance tests to our application and getting this error :S

**Comment by skaes** [comment] 2017-12-21 08:09
I still don't understand the problem. The call_tree_printer has a different signature on purpose. Can you please point me to a code example of the failing call?

**Comment by jywarren** [comment] 2018-01-02 17:40
Well, sorry, this was a few weeks ago, maybe "breaking change in the API" is overstating it -- but in any case our code wouldn't run on that version but it did on `v0.15.9` -- thanks a lot in any case!!!

**Comment by etewiah** [comment] 2018-01-30 11:07
Having the same issue with v0.17.0.  Pegged to v0.15.9 in my gemfile to work around this.
